### ISSUE TITLE
clarification: effect of transformations

### ISSUE THREAD

**Issue by johguenther** [KhronosGroup/ANARI-Docs#10]
We said that a transformation only applies to vectors, not to scalars / lengths (needs to be stated explicitly in the spec):
- thus `height` of orthographic camera is indeed in worlds units, regardless of a transform
- `radius` of point light with `KHR_AREA_LIGHTS` is not affected as well
- but `direction` of camera or `edge1` of quad light are transformed
- yet: geometries are not consistent to this convention, e.g., the `radius` of a sphere geometry will be transformed (even non-uniformly resulting in an ellipsoid)

**Comment by johguenther** [comment]
Leave it implementation-defined for now?

**Comment by jeffamstutz** [comment]
@johguenther yes, I think this should be implementation-defined for v1.0. In the future we are free to make a more prescriptive statement, but I don't think this is enough to be a show-stopper.
