### ISSUE TITLE
Incorrect table caption in section 5.10.5. (Transform sampler)

### ISSUE THREAD

**Issue by stukowski** [KhronosGroup/ANARI-Docs#106]
Current caption is: 

> Table 59. Parameters accepted by all `primitive` samplers.

but should be

> Table 59. Parameters accepted by all `transform` samplers.

Furthermore, sections 5.10.4 and 5.10.5 do not mention in the text what the names of the Primitive and Transform sampler types are that need to be passed to `anariNewSampler`.

**Comment by johguenther** [comment]
Thanks! Those are fixed in https://github.com/KhronosGroup/ANARI-Docs/pull/105 as well (e09524e3947db75ac9a8207d964d6f99e52da864)
