### ISSUE TITLE
Change anariDeviceImplements() to check any feature, not just exensions

### ISSUE THREAD

**Issue by jeffamstutz** [KhronosGroup/ANARI-Docs#20]
In order to unify all feature testing into a single API call, this proposal is to add feature names for all core features so there is a single list of all feature names that can be queried by the application. This has the added benefit of providing value to applications which use pre-compliant ANARI devices that may not have all core features implemented. This proposal adds the following to the specification:

- `anariDeviceImplements(ANARIDevice, const char *)` remains unchanged (just for this proposal, future forthcoming proposals are not to be excluded)
- The specification refers to all core features and core extensions under a common _feature_ definition: any API-correctness relevant concept in the API, namely object subtypes or required parameters.
- All features in the spec are prefixed with `ANARI_KHR_` and vendors should _not_ use this prefix for vendor extensions.
- The following is the list of feature names thus far:
```
ANARI_KHR_GEOMETRY_TRIANGLE
ANARI_KHR_GEOMETRY_QUAD
ANARI_KHR_GEOMETRY_SPHERE
ANARI_KHR_GEOMETRY_CONE
ANARI_KHR_GEOMETRY_CYLINDER
ANARI_KHR_GEOMETRY_CURVE
ANARI_KHR_SPATIAL_FIELD_STRUCTURED_REGULAR
ANARI_KHR_LIGHT_DIRECTIONAL
ANARI_KHR_LIGHT_POINT
ANARI_KHR_LIGHT_SPOT
ANARI_KHR_LIGHT_RING
ANARI_KHR_LIGHT_QUAD
ANARI_KHR_LIGHT_HDRI
ANARI_KHR_AREA_LIGHTS
ANARI_KHR_CAMERA_PERSPECTIVE
ANARI_KHR_CAMERA_ORTHOGRAPHIC
ANARI_KHR_CAMERA_OMNIDIRECTIONAL
ANARI_KHR_VOLUME_SCIVIS
ANARI_KHR_MATERIAL_MATTE
ANARI_KHR_MATERIAL_TRANSPARENT_MATTE
ANARI_KHR_SAMPLER_IMAGE_1D
ANARI_KHR_SAMPLER_IMAGE_2D
ANARI_KHR_SAMPLER_IMAGE_3D
ANARI_KHR_SAMPLER_PRIMITIVE_ID
ANARI_KHR_SAMPLER_TRANSFORM
ANARI_KHR_FRAME_COMPLETION_CALLBACK
ANARI_KHR_DEVICE_SYNCHRONIZATION
ANARI_KHR_TRANSFORMATION_MOTION_BLUR
ANARI_KHR_FRAME_AUXILIARY_BUFFERS
ANARI_KHR_STOCHASTIC_RENDERING
```

**Comment by jeffamstutz** [comment]
If issue #21 is also included, then device selection becomes a first-class feature and is expected to be a part of ANARI's initialization process for a device. Using the simple tutorial found in the SDK, the following becomes available to express the application's direct requirements:

```cpp
anari::Library lib = anari::loadLibrary("example");

bool usableDevice = anari::deviceImplements(lib, "default", {
  ANARI_KHR_GEOMETRY_TRIANGLE,
  ANARI_KHR_LIGHT_DIRECTIONAL,
  ANARI_KHR_CAMERA_PERSPECTIVE,
  ANARI_KHR_MATERIAL_MATTE
});

if (!usableDevice) {
    printf("ERROR: default device doesn't not support required features\n");
    return 1;
}

ANARIDevice d = anariNewDevice(lib, "default");

// ...
```

This has multiple advantages, primarily that the ANARI specification doesn't own the problem of identifying which features need to be tested: applications should espouse a culture of listing their _used_ features and this should not be countered by it being difficult. There are such a wide range of applications and rendering engines that ANARI is fit to support, that their required/optional feature lists are not something that ANARI should be in the business declaring "who's features are universal and who's features are not".

This idea would _remove no features_ which are currently defined in the spec, but may change the conformance requirement of their implementation by a device. Conformance would then be defined on a per-feature basis, where a "conforming device" for an application will be <= the features which the ANARI specifies -- giving language for an application to say "a conforming devices for application [X] must implement ANARI features [A, B, C, ...]".

**Comment by jeffamstutz** [comment]
This should add `ANARI_KHR_STEREO_CAMERAS` from #17.

**Comment by jeffamstutz** [comment]
Further going in this direction results in a nice, domain independent definition of what features must be required for a device to implement -- devices must implement a few features to _be testable at all_. In other words, in order to be able to detect if an object subtype functions correctly, certain other objects used in the test case must exist correctly. Thinking this through, I believe these are:

`ANARI_KHR_CAMERA_PERSPECTIVE`
`ANARI_KHR_GEOMETRY_TRIANGLE`
`ANARI_KHR_MATERIAL_MATTE`
`ANARI_KHR_LIGHT_DIRECTIONAL`

With these 4 features, you can then reliably test all other objects in the list. Thus if a device implements them, it can be declared "usable" and participate in the greater feature test suite.

**Comment by griffin28** [comment]
I would add: ANARI_KHR_GEOMETRY_SPHERE and ANARI_KHR_GEOMETRY_CYLINDER to the list.

**Comment by jeffamstutz** [comment]
Further WG discussions have brought up the idea of having baseline subtype robustness to counter the need to test the feature list for subtype existence. Thus with all the above there are multiple things proposed, each with its own sphere of influence:

- "testability" features are features required to test other features
- "conformance" is something forthcoming, but having "per feature" conformance makes the official adopter agreement applicable to the greatest number of possible vendors as it doesn't rule out vendors who disagree with us
- "feature testing" is only for detecting _ideal featureset_ (i.e. estimating implementation quality given a set of desired featurers) and _not_ for API usage correctness
- "domain minimum requirements" is an issue best suited for a separate standard: specs like 3D Commerce establish what the requirements are for a particular domain. Other domain specs could/should be created -- for example, "3D CAD", "3D SciVis", or "3D VFX", etc. All of these specs then ought to refer to collections of ANARI features, where ANARI merely defines how they work and the tests that confirm their correct implementation.

**Comment by johguenther** [comment]
Came with #41.
