### ISSUE TITLE
Add API call to return the complete list of extensions for a back-end device

### ISSUE THREAD

**Issue by griffin28** [KhronosGroup/ANARI-Docs#21]
This proposal is to add an API call to expose the complete list of extensions implemented by a back-end device. This proposal would add the following to the spec:

- `const char **anariGetDeviceExtensions(ANARIDevice d)` with a description of what the call is expected to do.

Also, the proposal would add roughly two lines of code to the SDK as shown below:

```
extern "C" const char **anariGetDeviceExtensions(ANARIDevice d)
{
    return deviceRef(d).getDeviceExtensions();
}
```

**Comment by progschj** [comment]
If the extension query happens on a device object we could use the already existinging `anariGetProperty` API call for this:

```
const char ** extensions;
int retrieved = anariGetProperty(device, device,
   "extensions", ANARI_STRING_LIST, &extensions,
   sizeof(extensions), ANARI_NO_WAIT);
//...
```
where `ANARI_STRING_LIST` would be a new entry in the `ANARIDataType` enum.

Some open questions would then be:

1. Is the returned list allowed to be dynamic based on external factors (hardware, driver, internal API versions etc.)?
2. If so is the property guaranteed to be available before the device has been committed? Availability of features could depend on device configuration set via parameters which would only take effect after commit.

**Comment by johguenther** [comment]
A 3rd alternative is similar to the other introspection calls (without the need to create a concrete device first):
```cpp
const char **anariGetDeviceFeatures(ANARILibrary, const char *deviceSubtype);
```

**Comment by johguenther** [comment]
> Is the returned list allowed to be dynamic based on external factors (hardware, driver, internal API versions etc.)?

Good question. For differentiation we said that Introspection is for static (compile-time) information while Properties are for dynamic (run-time dependent) information. Isn't most (all?) support for extensions static information?

**Comment by jeffamstutz** [comment]
>Isn't most (all?) support for extensions static information?

On the call today it was deemed there's a reasonable amount of evidence that a device may only have access to some features if the underlying infrastructure (i.e. HW) is available. For example, a Vulkan or DX12 based device may only offer a path tracing renderer (and any features inherently tied to that) if ray tracing extensions are available in VK/DX respectively. Thus the idea came up that there should be a static pathway to query what capabilities a device _could_ have from a library, then a property on the device itself that gives you a subset of that list that is _acutally_ available. Thus if you don't have a feature available at all in a library, there's no need to instantiated a device to find that out -- but there's also a pathway for devices to have HW-specific features known at runtime.

...so, both!

**Comment by johguenther** [comment]
We have this now as property query `feature` (returning a `STRING_LIST`) for ``DEVICE``s and ``RENDERER``s.
