### ISSUE TITLE
Combine transferFunction1D color + opacity arrays

### ISSUE THREAD

**Issue by jeffamstutz** [KhronosGroup/ANARI-Docs#82]
After discussing how the [colormap sampler idea](https://github.com/KhronosGroup/ANARI-Docs/issues/81) could entirely be implemented by `image1D` samplers (where color + opacity are in a single `image` array) _and_ due to the fact that there are not control points in the `transferFunction1D` volume, I think it makes sense to combine color + opacity arrays into a single `FLOAT32_VEC4` array. This simplifies applications by allowing them to have a single color map representation that is used to color map both surfaces and volumes.

**Comment by johguenther** [comment]
Even without control points the  `color` and `opacity` arrays can be of different size.

For materials we have a similar situation: having `color` and `opacity` separate, but if `color` if it is a `SAMPLER` additionally use the 4th channel as `opacity` as well.

So, have here both as well (`opacity` and `color` as `VEC3` and `VEC4`)?
