### ISSUE TITLE
Combine `intensityDistribution` and `intensity` for lights?

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/ANARI-Docs#95]
One could simplify `KHR_LIGHT_QUAD` and `KHR_LIGHT_RING` by combining these two parameters.
Just use the `intensity` parameter which can have type `FLOAT32` or `ARRAY1D` / `ARRAY2D` of `FLOAT32`.
This would be similar to the `color`/`opacity` parameter in volume.
Or is there a reason not to do this?

**Comment by johguenther** [comment]
After discussion in WG we like to keep parameters separate, for the reasons given above.
